= Modular Boost w/B2

This is a work-in-progress version of the Boost {CPP} Libraries that build as
modular components. What does it mean to be modular? It means that..

* Each library is separable from the rest.
* Each library does not assume a particular directory arrangement in a parent
  Boost super-project.
* The Boost super-project doesn't need to exist at all, only requirement is that
  library dependencies be pre-declared.
* No no need for creating the headers tree.
* Makes it possible for package managers, and hence users, to use the individual
  libraries they need.

== Goals

Generally the main goal is to move the main Boost git repos to a modular
structure over time without breaking any functionality. That is not an easy goal
to achieve. As there are 153 library repos, 12 tool repos, and the super project
repo to adjust along the way.

Happy to say though, that the bulk of the technical work is done. What's left
is to start merging pull requests for the transitional period. Then working on
followup changes to fully become the modular structure.

== Structure

To manage this effort safely there are a couple resources that I've created:

* A GitHub Project to keep track of the work.
* The "modular" super-project git repo.
* The "transitional" super-project forked git repo.
* Dozens of library and tool forked git repos with the modular PR changes.

== Project

There is a project to track the past, present, and future state of this effort
at https://github.com/users/grafikrobot/projects/1 with the following views:

* https://github.com/users/grafikrobot/projects/1/views/1[Overall Tech Tasks]:
This is mainly infrastructure type tasks that need to happen.

* https://github.com/users/grafikrobot/projects/1/views/2[Pull Requests]: The
PR's and their status against the mainline Boost repos.

* https://github.com/users/grafikrobot/projects/1/views/6[Merge Process]: How
to process the PRs for each Boost git repo. It's the result of asking all Boost
library maintainers if they would like to approve and merge PRs, or have the
Boost project owners do whatever is needed, or something else.

== Modular Super-Project

The modular super-project at https://github.com/grafikrobot/boost-b2-modular
follows a similar structure as the main Boost super-project repo.
It's composed of many git submodules for all the libraries, tools, and support
code with some differences:

* All submodules track the "modular" branch on each which holds the changes.

* There is only one tool submodule repo. The `tools/boost_build` project that
holds the build support installing and staging things like the monolithic
headers tree. Which is a dependency for the `libs/headers` submodule.

* There is no B2 project root. The only B2 file is a convenience (for testing)
`project-config.jam` file. It declares the B2 `/boost` project search locations.

Hence this git repo models the fully modular structure for libraries. As might
be seen from package manager, or from selective use of libraries in some other
project.

This git repo tests the ability to build each of the 153 libraries on Ubuntu
and Windows as a GitHub action
(https://github.com/grafikrobot/boost-b2-modular/actions/workflows/check-libs.yml)

== Transitional Super-Project

The transitional super-project at https://github.com/grafikrobot/boostorg.boost
is a fork of the Boost super-project develop branch (branched into the modular
branch). It contains the changes needed to create a transition from the
monolithic to the modular structure. And is the source of the super-project
PRs (indirectly and selectively). It has all the same Boost super-project
repo plus a few more utility tools to aid in the modular development.

It also has a series of CI checks as GitHub Actions:

* https://github.com/grafikrobot/boostorg.boost/actions/workflows/modular-check-libs.yml[Check Libraries]:
Identical to the modular checks except in this repo structure. Except it only
checks that B2 parses and declares the targets without errors. It doesn't try
to compile or run tests.

* https://github.com/grafikrobot/boostorg.boost/actions/workflows/ci.yml[CI]:
This is the same as the Boost super-project runs. Done here to verify it's as
green as the Boost super-project while making pre-PR changes.

* https://github.com/grafikrobot/boostorg.boost/actions/workflows/modular-release.yml[Modular Release]:
Runs an equivalent process as the Boost super-project to create a full release
snapshot. I.e. the same as what runs on Circle CI to create the release archives
the users download. Except it does it in the transitional structure.

== Technicalities

*_The main goal of the changes in this is to remove all references in build and
source files that assume the Boost libraries live in the monolithic directory
structure._*

But we also want to:

*