# Copyright 20242023 René Ferdinand Rivera Morell
# Use, modification, and distribution are subject to the
# Boost Software License, Version 1.0. (See accompanying file LICENSE.txt)

name: "Check Libraries"

on:
  # Allow manual runs.
  workflow_dispatch:
  push:
    branches:
      - modular

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        lib:
          - accumulators
          - algorithm
          - align
          - any
          - array
          - asio
          - assert
          - assign
          - atomic
          - beast
          - bimap
          - bind
          - callable_traits
          - charconv
          - chrono
          - circular_buffer
          - cobalt
          - compat
          - compatibility
          - compute
          - concept_check
          - config
          - container
          - container_hash
          - context
          - contract
          - conversion
          - convert
          - core
          - coroutine
          - coroutine2
          - crc
          - date_time
          - describe
          - detail
          - dll
          - dynamic_bitset
          - endian
          - exception
          - fiber
          - filesystem
          - flyweight
          - foreach
          - format
          - function
          - function_types
          - functional
          - fusion
          - geometry
          - gil
          - graph
          - graph_parallel
          - hana
          - headers
          - heap
          - histogram
          - hof
          - icl
          - integer
          - interprocess
          - interval
          - intrusive
          - io
          - iostreams
          - iterator
          - json
          - lambda
          - lambda2
          - leaf
          - lexical_cast
          - local_function
          - locale
          - lockfree
          - log
          - logic
          - math
          - metaparse
          - move
          - mp11
          - mpi
          - mpl
          - msm
          - multi_array
          - multi_index
          - multiprecision
          - mysql
          - nowide
          - numeric_conversion
          - odeint
          - optional
          - outcome
          - parameter
          - parameter_python
          - pfr
          - phoenix
          - poly_collection
          - polygon
          - pool
          - predef
          - preprocessor
          - process
          - program_options
          - property_map
          - property_map_parallel
          - property_tree
          - proto
          - ptr_container
          - python
          - qvm
          - random
          - range
          - ratio
          - rational
          - redis
          - regex
          - safe_numerics
          - scope
          - scope_exit
          - serialization
          - signals2
          - smart_ptr
          - sort
          - spirit
          - stacktrace
          - statechart
          - static_assert
          - static_string
          - stl_interfaces
          - system
          - test
          - thread
          - throw_exception
          - timer
          - tokenizer
          - tti
          - tuple
          - type_erasure
          - type_index
          - type_traits
          - typeof
          - ublas
          - units
          - unordered
          - url
          - utility
          - uuid
          - variant
          - variant2
          - vmd
          - wave
          - winapi
          - xpressive
          - yap
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "bash"
        working-directory: ${{github.workspace}}/boostroot
    steps:
      - name: "Setup"
        working-directory: ${{github.workspace}}
        run: |
          sudo apt-get -o Acquire::Retries=3 update
          sudo apt-get -o Acquire::Retries=3 -y install g++-13 liburing-dev
      - name: "Checkout Boost Root"
        uses: actions/checkout@main
        with: { submodules: true, path: "boostroot" }
      - name: "Checkout B2"
        uses: actions/checkout@main
        with: { repository: "bfgroup/b2", path: "b2" }
      - name: B2
        working-directory: ${{github.workspace}}/b2
        run: ./bootstrap.sh
      - name: Check
        run: '"${{github.workspace}}/b2/b2" --debug-configuration "--build-dir=${{github.workspace}}/bin" --remove-test-targets toolset=gcc-13 cxxstd=20 libs/${{matrix.lib}}//all'
  windows:
    strategy:
      fail-fast: false
      matrix:
        lib:
          - accumulators
          - algorithm
          - align
          - any
          - array
          - asio
          - assert
          - assign
          - atomic
          - beast
          - bimap
          - bind
          - callable_traits
          - charconv
          - chrono
          - circular_buffer
          - cobalt
          - compat
          - compatibility
          - compute
          - concept_check
          - config
          - container
          - container_hash
          - context
          - contract
          - conversion
          - convert
          - core
          - coroutine
          - coroutine2
          - crc
          - date_time
          - describe
          - detail
          - dll
          - dynamic_bitset
          - endian
          - exception
          - fiber
          - filesystem
          - flyweight
          - foreach
          - format
          - function
          - function_types
          - functional
          - fusion
          - geometry
          - gil
          - graph
          - graph_parallel
          - hana
          - headers
          - heap
          - histogram
          - hof
          - icl
          - integer
          - interprocess
          - interval
          - intrusive
          - io
          - iostreams
          - iterator
          - json
          - lambda
          - lambda2
          - leaf
          - lexical_cast
          - local_function
          - locale
          - lockfree
          - log
          - logic
          - math
          - metaparse
          - move
          - mp11
          - mpi
          - mpl
          - msm
          - multi_array
          - multi_index
          - multiprecision
          - mysql
          - nowide
          - numeric_conversion
          - odeint
          - optional
          - outcome
          - parameter
          - parameter_python
          - pfr
          - phoenix
          - poly_collection
          - polygon
          - pool
          - predef
          - preprocessor
          - process
          - program_options
          - property_map
          - property_map_parallel
          - property_tree
          - proto
          - ptr_container
          - python
          - qvm
          - random
          - range
          - ratio
          - rational
          - redis
          - regex
          - safe_numerics
          - scope
          - scope_exit
          - serialization
          - signals2
          - smart_ptr
          - sort
          - spirit
          - stacktrace
          - statechart
          - static_assert
          - static_string
          - stl_interfaces
          - system
          - test
          - thread
          - throw_exception
          - timer
          - tokenizer
          - tti
          - tuple
          - type_erasure
          - type_index
          - type_traits
          - typeof
          - ublas
          - units
          - unordered
          - url
          - utility
          - uuid
          - variant
          - variant2
          - vmd
          - wave
          - winapi
          - xpressive
          - yap
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: ${{github.workspace}}/boostroot
    steps:
      - name: "Checkout Boost Root"
        uses: actions/checkout@main
        with: { submodules: true, path: "boostroot" }
      - name: "Checkout B2"
        uses: actions/checkout@main
        with: { repository: "bfgroup/b2", path: "b2" }
      - name: B2
        working-directory: ${{github.workspace}}/b2
        run: bootstrap.bat
      - name: Check
        run: '"${{github.workspace}}/b2/b2" --debug-configuration "--build-dir=${{github.workspace}}/bin" --remove-test-targets toolset=msvc cxxstd=20 libs/${{matrix.lib}}//all' -DBOOST_ALL_NO_LIB
